# Generated by Django 5.0 on 2025-08-15 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dniPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHistorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField()),
                ('dniMedico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='medicos.medico')),
                ('idHistorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='historiales.historialmedico')),
            ],
        ),
    ]
