# Generated by Django 5.0 on 2025-08-19 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0001_initial'),
        ('pacientes', '0002_alter_responsable_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='dniPaciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pacientes.paciente'),
        ),
    ]
