# Generated by Django 5.0 on 2025-09-23 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estadoAsistencia', models.BooleanField(default=False)),
                ('dniMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='medicos.medico')),
                ('dniPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoPago', models.BooleanField(default=False)),
                ('idTurno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='turnos.turno')),
            ],
        ),
    ]
