# Generated by Django 5.0 on 2025-08-15 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('dniMedico', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('especialidad', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('dniMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='medicos.medico')),
            ],
        ),
    ]
