# Generated by Django 5.0 on 2025-08-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_medico_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='diaSemana',
            field=models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes')], default='LUN', max_length=3),
        ),
    ]
