# Generated by Django 5.0 on 2025-08-15 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('dniPaciente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.TextField()),
                ('tipoSangre', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('dniResponsable', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.TextField()),
                ('tipoSangre', models.CharField(max_length=5)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='pacientes.paciente')),
            ],
        ),
    ]
