# Generated by Django 5.0 on 2025-09-23 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historiales', '0001_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohistorial',
            name='dniMedico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='medicos.medico'),
        ),
        migrations.AddField(
            model_name='registrohistorial',
            name='idHistorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='historiales.historialmedico'),
        ),
    ]
